### ISSUE TITLE
Packages refactoring proposal

### ISSUE THREAD

**Issue by cgendreau** [gbif/dwca-io#13]
In the same spirit as renaming the project for 'dwca-io', I would like to propose a packages refactoring.
The idea is to split the classes inside the current `org.gbif.dwc.text` package into 'reader' and 'writer' packages.

 - org.gbif.dwc(a).writer
  - DwcaWriter
 - org.gbif.dwc(a).reader
  - ArchiveFactory

**Comment by cgendreau** [comment]
Another idea:
 * Rename `org.gbif.dwc.text` to `org.gbif.io.dwc`
 * Move classes of this project currently in `org.gbif.file` to the new `org.gbif.io` package

**Comment by mdoering** [comment]
I like org.gbif.io(.dwca) even better, give it a try

**Comment by cgendreau** [comment]
First step includes:
org.gbif.file -> org.gbif.io
org.gbif.dwc -> org.gbif.dwca
org.gbif.dwc.text -> org.gbif.dwca.io

My suggested `org.gbif.io.dwc` package was not very suitable for other packages like `record` and `tools` so it would have required a `org.gbif.dwca` packages in that case too. In order to keep `dwca` related classes closer, I decided to rename `org.gbif.dwc.text` to `org.gbif.dwca.io` instead of renaming/moving `text` to `org.gbif.io.dwca`.
