### ISSUE TITLE
Possible incorrect rowType in generated meta.xml

### ISSUE THREAD

**Issue by cgendreau** [gbif/dwca-io#15]
Previously, the `rowType` field of the class `ArchiveFile` was a String but it has been [changed](https://github.com/gbif/dwca-io/commit/93f452a0f59b80cec39d1894f999a0a5d0a3dcf1) to `Term`, which makes sense.
A side effect of that appears in the `meta.ftl` template where the code `rowType="${core.rowType}"` is used. This will use the `toString()` from the enum and write something like `rowType="dwc:Occurrence"` in the generated meta.xml. I think the ftl template should be updated with something like `rowType="${core.rowType.qualifiedName}"`

Am I correct?

P.S. The generated meta.xml can be read back by the `dwca-io` without issues since `TermFactory` will recognize it.

**Comment by mdoering** [comment]
Very right indeed. The ftl expression should be `rowType="${core.rowType.qualifiedName()}"`
