### ISSUE TITLE
Prominent link to mvn artifacts would be welcome

### ISSUE THREAD

**Issue by ramorrismorris** [gbif/dwca-io#17]
Somewhere in prominent documentation, a simple set of maven props would be welcome.  The only thing I found easily on the web was http://dev.gbif.org/wiki/display/DEV/GBIF+Maven+Repository from which I needed to work out for myself that 

```
  <repositories>
    <repository>
        <id>gbif-all</id>
        <url>http://repository.gbif.org/content/groups/gbif</url>
    </repository>
   </repositories>




   <dependency>
        <groupId>org.gbif</groupId>
        <artifactId>dwca-io</artifactId>
        <version>1.23</version>
    </dependency>
```

-->
would work.  A google search for    gbif maven   comes to the wiki discussion of details of interest mainly to committers, and a little sparse for projects that simply depend on dwc-io.  This is probably true for most of the GBIF projects hosted in github.  For most of us, setting up dependencies should be simple cut and paste, and it should be an easy click or two to an interface that finds them.

**Comment by cgendreau** [comment]
I agree, I'm sending the Pull Request

**Comment by mdoering** [comment]
Fully agree, we need to document the GBIF maven repo somewhere centrally. But as a start its great to include it here already in the examples at least

**Comment by cgendreau** [comment]
Done in https://github.com/gbif/dwca-io/pull/18
But like @mdoering suggested, it would be nice to have documented centrally.
