### ISSUE TITLE
Allow escape characters to be defined in meta.xml

### ISSUE THREAD

**Issue by charvolant** [gbif/dwca-io#19]
At the moment, meta.xml allows fieldsEnclosedBy="&quot;"  in a core or extension element.

In some cases, particularly with complex fields, such as names or citations, the enclosing character may appear in the text, as well. Generally, with CSV files, it's possible to escape the enclosure marker, so that an entry such as `Melaleuca bracteata "Golden Gem"` could be encoded as `"Melaleuca bracteata \"Golden Gem\""`

**Comment by mdoering** [comment]
But you can escape quote characters already, it is just not the backslash or a custom way. We use the StrTokenizer from apache commons lang3 to tokenize string rows into string arrays. You simply have to use the quoted character twice:


I have added tests to show that behavior:
https://github.com/gbif/dwca-io/blob/master/src/test/java/org/gbif/io/CSVReaderTest.java#L56

**Comment by mdoering** [comment]
... adding a new attirbute to meta.xml would require a (ratified) change to the Darwin Core standard which is a longer process

**Comment by charvolant** [comment]
Ta muchly
