### ISSUE TITLE
Classification delimiter

### ISSUE THREAD

**Issue by tucotuco** [gbif/dwca-io#2]
As of 30 Oct 2014 the higherClassification term now carries the comment "The recommended best practice is to separate the values with a vertical bar (' | '), with terms in order from the highest taxonomic rank to the lowest. 

Recommend to change 

https://github.com/gbif/dwca-reader/blob/903d10236b3b2cda46a0d2b3e994e0ce658c328e/src/main/java/org/gbif/dwc/record/DarwinCoreTaxon.java#L17

to 

private static final String CLASSIFICATION_DELIMITER = " | ";

**Comment by mdoering** [comment]
done https://github.com/gbif/dwca-io/blob/05c44d16c1514ad3c95848af71852457024abe5d/src/main/java/org/gbif/dwca/record/DarwinCoreTaxon.java#L17
