### ISSUE TITLE
Detection of ID column in CSV should not use a leftmost approach

### ISSUE THREAD

**Issue by cgendreau** [gbif/dwca-io#25]
Currently, we assign the ID column to use by taking the first known ID column from the left.
While this approach works most of the time, we should have a predefined order that will not vary depending on the ordering of the columns as submitted by the user.

The new rule will be the first term found in the header based on this list:
`DwcTerm.occurrenceID, DwcTerm.taxonID, DwcTerm.eventID, DcTerm.identifier`

**Comment by MattBlissett** [comment]
This looks to have been completed by Christian's commit last year.
