### ISSUE TITLE
ArchiveFile is missing defaults from Darwin Core Text Guide

### ISSUE THREAD

**Issue by ansell** [gbif/dwca-io#29]
ArchiveFile does not define initial values for fieldsTerminatedBy, rowType, or fieldsEnclosedBy, which all have defaults defined in the Darwin Core Text Guide:

http://rs.tdwg.org/dwc/terms/guides/text/

This causes failures on Darwin Core Archives which were designed based on the spec and did not repeat these values.

**Comment by ansell** [comment]
rowType is ambiguous because it also says it is "required", so this issue is mostly about fieldsTerminatedBy and fieldsEnclosedBy

**Comment by cgendreau** [comment]
fixed on dwca-io-1.31
