### ISSUE TITLE
Shade Guava

### ISSUE THREAD

**Issue by ansell** [gbif/dwca-io#32]
The use of Google Guava as an explicit dependency is limiting reuse of dwca-io by other GBIF libraries and third-parties such as ALA by enforcing a large testing regime before verifying that new guava versions with bug fixes and new features can be used here.

Guava should be shaded in the same way as Jackson is shaded currently for gbif-common, removing it as an obstacle to reuse of this library.

**Comment by timrobertson100** [comment]
See also #39
