### ISSUE TITLE
ArchiveField extends Darwin Core Text Guide with delimitedBy

### ISSUE THREAD

**Issue by ansell** [gbif/dwca-io#34]
The ``ArchiveField`` class supports an extension to the Darwin Core Text Guide with the addition of a ``delimitedBy`` field, presumably to indicate that a field contains multiple values that can be split on this character. I noticed this as I was examining why a download from GBIF contains the non-standard ``delimitedBy`` attribute on a ``field``, which I did not have implemented for my software that was written based on the published spec.

Is it possible to keep the Darwin Core Text Guide up-to-date with changes like this to avoid dwca-io (and GBIF Darwin Core Archives Downloads) being incompatible with the published specification and other Darwin Core Archive implementations?

**Comment by cgendreau** [comment]
The `delimitedBy` is defined in the XSD, see https://github.com/tdwg/dwc/blob/master/text/tdwg_dwc_text.xsd#L108

It is possible to update the Darwin Core Text Guide by providing a pull request to @tdwg on 
https://github.com/tdwg/dwc.

**Comment by ansell** [comment]
Thanks for the reference to the XSD. Closing this now as it isn't an issue here.
