### ISSUE TITLE
Better handling of metadata only "archive"

### ISSUE THREAD

**Issue by cgendreau** [gbif/dwca-io#35]
This library can open a metadata only file but it works by chance. The EML is handled as a CSV (a broken one) and we end up with a (bogus) core but we can get the metadata from the `Archive`.

Instead, the library should allow an `Archive` object to have no core (and no extension) and only a metadata document. Basically, a DarwinCore file with no records, only metadata.

We need to check for potential issues since the core was considered mandatory.

**Comment by mdoering** [comment]
Makes sense to allow for metadata only. Methods requiring a core like the record iterators should then return an exception, maybe specific to metadata only, e.g. NoDataException.

**Comment by MattBlissett** [comment]
In removing the dependencies on GBIF components (i.e. the registry), I removed dwca-io parsing EML files.

That makes it a bit pointless to do anything with just an EML file, so this isn't relevant any more.
