### ISSUE TITLE
TemplateException (meta.ftl not found) in MetaDescriptorWriter.writeMetaFile()

### ISSUE THREAD

**Issue by lsuhrbier** [gbif/dwca-io#38]
When using MetaDescriptorWriter.writeMetaFile(), then a TemplateException with cause "meta.ftl not found" is raised up. 

This is due to line 66 in MetaDeskriptorWriter#provideFreemarker():
TemplateLoader tl = new ClassTemplateLoader(EMLWriter.class, TEMPLATE_PATH);

The EMLWriter.class is in org.gbif.registry.metadata.jar, but the /templates directory containing meta.ftl is in org.gbif.dwca-io.jar. So, the template classloader fpr EMLWriter can not find the meta.ftl resource. 

Solution: change line 66 into:
TemplateLoader tl = new ClassTemplateLoader(MetaDescriptorWriter.class, "/templates");

Then, the meta.ftl template is found !

Other solutions either move the /templates dir to  org.gbif.registry.metadata.jar, or pull the org.gbif.registry.metadata into org.gbif.dwca-io.jar !

**Comment by cgendreau** [comment]
Thanks for reporting the issue, the class used with `ClassTemplateLoader` was indeed the wrong one.
