### ISSUE TITLE
Deprecate ArchiveFactory ?

### ISSUE THREAD

**Issue by cgendreau** [gbif/dwca-io#43]
Discussion started on Issue #42.

As version 1.32, `ArchiveFactory` and `DwcFiles` both offer methods to create `Archive` objects which is confusing. `ArchiveFactory` is currently calling `DwcFiles` to build its objects but also performs additional validations (e.g. check that `getLocationFile() != null`) that current callers may rely on.

**Comment by MattBlissett** [comment]
This was done, ArchiveFactory was removed in the big refactor.
