### ISSUE TITLE
Missing quotes in occurrence sorted files

### ISSUE THREAD

**Issue by asturcon** [gbif/dwca-io#46]
When parsing occurrences with a catalog number different from the occurrence id, at the time of sorting the occurrences the quotes are deleted from the catalog number, which leads to skip those occurrences in the dwc reading process. 

We also noticed that if we replace the catalog number with the occurrence id it works fine.

For example, this line in occurrence.txt:
```
"20110731whk01a","BGBM","BoBO","HumanObservation","c53b39f4-4bc5-4e3b-9771-76243d95adee",,,"W.-H.Kusber",,,,,,"31",,,,,,,"Germany","DE","Brandenburg, Wiese bei Körzin",,"2011-07-31T00:00:00",,,,,,,,,"52.22101","13.09464","15",,,,,,,,,,,"Europe",,"Sabine von Mering",,,,,,"Triglochin maritima L.",,,"Plantae; Magnoliophyta; Magnoliopsida; Najadales; Juncaginaceae","Plantae",,"Magnoliopsida","Najadales","Juncaginaceae","Triglochin",,"maritima",,,
```
is converted to this one in occurrence.txt-sorted:
```
20110731whk01a,BGBM,BoBO,HumanObservation,"c53b39f4-4bc5-4e3b-9771-76243d95adee",,,W.-H.Kusber,,,,,,31,,,,,,,Germany,DE,"Brandenburg, Wiese bei Körzin",,2011-07-31T00:00:00,,,,,,,,,52.22101,13.09464,15,,,,,,,,,,,Europe,,"Sabine von Mering",,,,,,"Triglochin maritima L.",,,"Plantae; Magnoliophyta; Magnoliopsida; Najadales; Juncaginaceae",Plantae,,Magnoliopsida,Najadales,Juncaginaceae,Triglochin,,maritima,,,
```
 You can find this example in this dataset in DEV crawler:

`storage/dwca/e1beb83c-9b83-4d17-ac5e-d24e09507ec5`

**Comment by cgendreau** [comment]
Could you provide the meta.xml file please?

**Comment by asturcon** [comment]
Here it is the meta.xml:

[meta.xml.zip](https://github.com/gbif/dwca-io/files/1879807/meta.xml.zip)

**Comment by MattBlissett** [comment]
Yes, this was fixed.
