### ISSUE TITLE
deploy to maven central

### ISSUE THREAD

**Issue by jhpoelen** [gbif/dwca-io#55]
Hi!

I've been using dwca-io for many years now in https://github.com/globalbioticinteractions/globalbioticinteractions . 

Now that I am looking to migrate away from a custom maven repo and use maven central for sustainability reasons (maven central is used, and maintained by, many), I noticed that dwca-io is one of the few dependencies that has not yet been deployed to maven central. 

Do you have any plans to deploy your artifacts to Maven Central?

**Comment by MattBlissett** [comment]
Hi Jorrit,

We don't have any plan to deploy the artefacts to Maven Central.  

We've run our [Nexus repository](https://repository.gbif.org/) for around 10 years, others (e.g. ALA) mirror it, and we're confident we will continue to support it.

**Comment by jhpoelen** [comment]
@MattBlissett thanks for responding. Great to hear that ALA is mirroring your repository and that you are confident that the GBIF's nexus repository will stick around for a while. 

However, please see https://maven.apache.org/repository/guide-central-repository-upload.html -

```
I have other repositories or pluginRepositories listed in my POM, is that a problem?

At present, this won't preclude your project from being included, but we do strongly encourage making sure all your dependencies are included in the Central Repository. If you rely on sketchy repositories that have junk in them or disappear, it just creates havok for downstream users. Try to keep your dependencies among reliable repos like Central, Jboss, etc.
```
