### ISSUE TITLE
Column separator detection is going wrong

### ISSUE THREAD

**Issue by sylmorin-gbif** [gbif/dwca-io#57]
We have some (weird) datasets with a single occurrence, describing the presence of a species at multiple locations on a wide time range (like a synthesis).

As a consequece, the municipality field has lots of values separated by | character.

The column seperator detection (https://github.com/gbif/gbif-common/blob/master/src/main/java/org/gbif/utils/file/tabular/TabularFileMetadataExtractor.java) is going wrong because there are far more | character than ; character is this CSV.

We had to patch the dwca-io lib to hardcode the column separator to ;

It would be great if it can be configurable (auto detection by default or overriden by configuration)

**Comment by mdoering** [comment]
I would recommend declaring the [fieldsTerminatedBy](https://dwc.tdwg.org/text/#2-metafile-content) in the meta.xml file of the DwC archive.

**Comment by sylmorin-gbif** [comment]
Thank you @mdoering 
I didn't notice, in the dwca-io code, that is was reading configuration from meta.xml.
I will test it because it's totally what I need.

About how suspicious this dataset sounds, you're totally right, and I reported it several times, but it's a highly sensitive topic (this data producer is only sharing aggregated data....)

**Comment by sylmorin-gbif** [comment]
Hello,

I confirm that it's working fine by adding the meta.xml file to configure the column separator.
The ALA pipeline is now ingesting correctly our dataset.

Thank you.
