### ISSUE TITLE
Support mulitple files per rowType

### ISSUE THREAD

**Issue by mdoering** [gbif/dwca-io#59]
iNat produces a DwCA with many files per rowType which is allowed according to dwca specs.
The Archive class already holds a list of locations, but the iterators then only use the first one provided.
From ArchiveFile:

`   * TODO: check if we got more than 1 file and implement some unix concat into a single file first before sorting that
`
https://www.inaturalist.org/taxa/inaturalist-taxonomy.dwca.zip

**Comment by timrobertson100** [comment]
In helpdesk, we have received a similar report of this from a Specify7 publisher

KUBI Ichthyology Tissue collection - https://ichthyology.specify.ku.edu/static/depository/export_feed/kuit-dwca.zip
KUBI Ichthyology Voucher collection - https://ichthyology.specify.ku.edu/static/depository/export_feed/kui-dwca.zip

Example:

```
<extension rowType="http://rs.tdwg.org/ac/terms/Multimedia" fieldsEnclosedBy="&quot;" fieldsTerminatedBy="," linesTerminatedBy="\r\n">
		<files>
			<location>COAudubonCore.csv</location>
			<location>CEAudobonCore.csv</location>
		</files>
		<coreid index="0"/>
```
