### ISSUE TITLE
question: is dwca-io still actively developed?

### ISSUE THREAD

**Issue by jhpoelen** [gbif/dwca-io#64]
Hi! 

Thanks for helping to keep dwca-io library available and working. I've used it for many years now.

Before asking more technical questions, I was wondering - 

Is dwca-io still actively maintained?

If not, what is the replacement library / method to reading DwC-A?

thx,
-jorrit

**Comment by jhpoelen** [comment]
Does this reference to dwca-io in the pipelines repository answer my own question? 

https://github.com/gbif/pipelines/blob/ddd3afc604667d914d55c3ab6f194db0e2f036a1/sdks/core/pom.xml#L102

**Comment by jhpoelen** [comment]
@timrobertson100 thanks for confirming!

**Comment by timrobertson100** [comment]
You're very welcome

Feel free to post requests, or PRs if you care to. Please be aware it could be used in a lot of places so there may be some reluctance to change existing APIs or dependencies, but I'm sure solutions could be found.
